site_name: Oferta Académica
site_url: https://universidad-aaron2913.github.io/oferta/

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Inicio: index.md
  - Facultades:
      - Ingeniería: facultades/ingenieria.md
      - Ciencias Sociales: facultades/ciencias_sociales.md
      - Salud: facultades/salud.md
      - Administración: facultades/administracion.md