site_name: Oferta Académica UTPL

nav:
  - Inicio: oferta/index.md
  - Facultades:
      - Ingeniería: facultades/ingenieria.md
      - Ciencias Sociales: facultades/ciencias_sociales.md
      - Salud: facultades/salud.md
      - Administración: facultades/administracion.md